//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conv2WebP4Win {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("conv2WebP4Win.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zainstaluj.
        /// </summary>
        internal static string btnInstall {
            get {
                return ResourceManager.GetString("btnInstall", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik nie jest obsługiwanym formatem graficznym (JPG/JPEG lub PNG)..
        /// </summary>
        internal static string convBadFormat {
            get {
                return ResourceManager.GetString("convBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik {0} już istnieje. Czy chcesz go nadpisać?.
        /// </summary>
        internal static string convFileExists {
            get {
                return ResourceManager.GetString("convFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd podczas konwersji:\n\n{0}.
        /// </summary>
        internal static string convRunError {
            get {
                return ResourceManager.GetString("convRunError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik został pomyślnie przekonwertowany do WebP:\n{0}.
        /// </summary>
        internal static string convSuccessConv {
            get {
                return ResourceManager.GetString("convSuccessConv", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik Istnieje.
        /// </summary>
        internal static string genErrFileExists {
            get {
                return ResourceManager.GetString("genErrFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd.
        /// </summary>
        internal static string genError {
            get {
                return ResourceManager.GetString("genError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd podczas instalacji:\n\n{0}.
        /// </summary>
        internal static string genErrorMsg {
            get {
                return ResourceManager.GetString("genErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Instalacja nie powiodła się..
        /// </summary>
        internal static string genFailed {
            get {
                return ResourceManager.GetString("genFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Instalacja ImageMagick nie powiedła się..
        /// </summary>
        internal static string genIMError {
            get {
                return ResourceManager.GetString("genIMError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sukces.
        /// </summary>
        internal static string genSuccess {
            get {
                return ResourceManager.GetString("genSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gotowy do instalacji.
        /// </summary>
        internal static string labelReady {
            get {
                return ResourceManager.GetString("labelReady", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ta aplikacja zainstaluje konwerter grafiki do formatu WebP i doda odpowiednie pozycje do menu kontekstowego Windows..
        /// </summary>
        internal static string labelSTitle {
            get {
                return ResourceManager.GetString("labelSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Konwerter JPG/PNG do WebP - Instalator.
        /// </summary>
        internal static string labelTitle {
            get {
                return ResourceManager.GetString("labelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ta aplikacja wymaga uprawnień administratora. Uruchom ponownie jako administrator..
        /// </summary>
        internal static string msgAdmin {
            get {
                return ResourceManager.GetString("msgAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik nie istnieje: {0}.
        /// </summary>
        internal static string msgFileNotExists {
            get {
                return ResourceManager.GetString("msgFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Instalacja zakończona pomyślnie!\n\nMożesz teraz konwertować pliki JPG i PNG do formatu WebP poprzez menu kontekstowe..
        /// </summary>
        internal static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Konwertuj do WebP.
        /// </summary>
        internal static string regEntry {
            get {
                return ResourceManager.GetString("regEntry", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tworzenie katalogu instalacyjnego....
        /// </summary>
        internal static string statUpd {
            get {
                return ResourceManager.GetString("statUpd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tworzenie pliku konwertera....
        /// </summary>
        internal static string statUpd1 {
            get {
                return ResourceManager.GetString("statUpd1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodawanie wpisów do rejestru Windows....
        /// </summary>
        internal static string statUpd2 {
            get {
                return ResourceManager.GetString("statUpd2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Instalacja zakończona pomyślnie!.
        /// </summary>
        internal static string statUpd3 {
            get {
                return ResourceManager.GetString("statUpd3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sprawdzanie, czy ImageMagick jest zainstalowany....
        /// </summary>
        internal static string statUpdIM {
            get {
                return ResourceManager.GetString("statUpdIM", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pobieranie ImageMagick....
        /// </summary>
        internal static string statUpdIM2 {
            get {
                return ResourceManager.GetString("statUpdIM2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Instalowanie ImageMagick....
        /// </summary>
        internal static string statUpdIM3 {
            get {
                return ResourceManager.GetString("statUpdIM3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ImageMagick jest już zainstalowany..
        /// </summary>
        internal static string statUpdIM4 {
            get {
                return ResourceManager.GetString("statUpdIM4", resourceCulture);
            }
        }
    }
}
